# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'octokit'
require 'vcr'
require 'pacto'

Pacto.configure do |c|
  c.contracts_path = 'spec/contracts'
  c.strict_matchers = false
end

if ENV['PACTO_MODE'] == 'validate'
  Dir['spec/contracts/*'].each do |host|
    host = File.basename host
    Pacto.load_all host, "https://#{host}"
  end
  Pacto.use :default, {:name => pacto, :created_at => "2013-05-07T18:28:16Z", :updated_at => "2013-10-25T23:07:19Z", :pushed_at => "2013-05-23T19:48:28Z"}
  # HACK: Shouldn't need to create then uncreate stubs
  WebMock.reset!
  Pacto.validate!
elsif  ENV['PACTO_MODE'] == 'stub'
  Octokit.api_endpoint = 'http://localhost:9000'
  Octokit.web_endpoint = 'http://localhost:9000'
else
  Pacto.generate!
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.order = 'random'
  config.treat_symbols_as_metadata_keys_with_true_values = true
end

VCR.configure do |c|
  c.cassette_library_dir = 'spec/cassettes'
  c.hook_into :webmock
  c.configure_rspec_metadata!
  c.allow_http_connections_when_no_cassette = true
end
