# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'octokit'
require 'vcr'
require 'pacto'

Pacto.configure do |c|
  c.contracts_path = 'spec/contracts'
  c.strict_matchers = false
end

if ENV['PACTO_MODE'] == 'validate'
  Dir['spec/contracts/*'].each do |host|
    host = File.basename host
    Pacto.load_all host, "https://#{host}"
  end
  Pacto.use :default
  # HACK: Shouldn't need to create then uncreate stubs
  WebMock.reset!
  Pacto.validate!
else
  Pacto.generate!
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

VCR.configure do |c|
  c.cassette_library_dir = 'spec/cassettes'
  c.hook_into :webmock
  c.configure_rspec_metadata!
  c.allow_http_connections_when_no_cassette = true
end



RSpec.configure do |c|
  # so we can use :vcr rather than :vcr => true;
  # in RSpec 3 this will no longer be necessary.
  c.treat_symbols_as_metadata_keys_with_true_values = true
end